// src/components/Home/Section/RecruitmentSolutions.tsx
import useTailwindConfig from '@/hooks/useTailwindConfig';
import { Bricolage_Grotesque } from 'next/font/google';
import Section from './Section';
import { ArrowUpRight, Bolt, ChartLine, CircleArrowUp } from 'lucide-react';
import { Button } from '@/components/custom/button';
import Link from 'next/link';
import Image from 'next/image';

const bricolageGrotesque = Bricolage_Grotesque({
    variable: '--font-bricolage-grotesque',
    subsets: ['latin'],
  });

export default function RecruitmentSolutions() {
  const { heading2 } = useTailwindConfig();
  const listItems = [
    {
      icon: Bolt,
      title: 'Customized Talent Sourcing',
      description:
        'We tailor our recruitment process to find candidates who match your needs and company culture.',
    },
    {
      icon: ChartLine,
      title: 'Streamlined Hiring Process',
      description:
        'We manage the entire recruitment lifecycle, helping you attract top talent quickly and efficiently.',
    },
  ];
  return (
    <Section
      inverse
      rightGrid={
        <div className="flex flex-col h-full justify-between">
          <div className="flex flex-col gap-4 pb-12">
            <h1 className={heading2}>
              Recruitment Solutions tailored to your needs
            </h1>
            <p className="text-muted-foreground">
              Our mission is to create a global movement of compassion, uniting
              individuals and organizations.
            </p>

            <Button
              variant={'outline'}
              className="flex w-fit !p-5 md:!p-7 justify-center items-center"
            >
              <Link href="/" className="text-sm md:text-base">
                Partner With Us
              </Link>
              <ArrowUpRight />
            </Button>
          </div>

          <ul className="flex flex-col gap-5  border-t border-muted-foreground/30 pt-12">
            {listItems.map((list, index) => {
              return (
                <ListItem
                  key={index}
                  title={list.title}
                  description={list.description}
                  icon={list.icon}
                ></ListItem>
              );
            })}
          </ul>
        </div>
      }
      leftGrid={
        <>
          <div className='relative'>
            <Image
              className="size-full object-cover"
              src="/recruitment.png"
              width="500"
              height="500"
              alt="Section Image"
            />
            <div className={`absolute  flex flex-col gap-2.5 bottom-5 left-5 size-fit bg-white text-[#333] p-6 ${bricolageGrotesque.className} rounded-2xl z-10`}>
              <p className='text-5xl font-medium'>99%+</p>
              <p className='text-base max-w-36'>Quick Talent Acquisition</p>
              <p className='flex items-center gap-1 text-xs text-green-500 font-medium'>+56%<CircleArrowUp className='fill-green-500 text-white size-4' /></p>
            </div>
          </div>
        </>
      }
    />
  );
}

function ListItem({
  title,
  description,
  icon: Icon,
}: {
  title: string;
  description: string;
  icon: React.ForwardRefExoticComponent<React.SVGProps<SVGSVGElement>>;
}) {
  const { subHeading, paragraph } = useTailwindConfig();
  return (
    <li className="flex gap-2.5 font-[Clash_Display] text-sm md:text-base lg:text-lg">
      <Icon className="shrink-0 size-6 md:size-8 lg:size-10" strokeWidth={1.5} />
      <div className="flex flex-col gap-2.5">
        <h2 className={`${subHeading}`}>{title}</h2>
        <p className={`${paragraph}`}>{description}</p>
      </div>
    </li>
  );
}

// apps/site/app/components/Home/RecruitmentSolutions.vue
<script setup lang="ts">
import { ArrowUpRight, Bolt, ChartLine, CircleArrowUp } from "@lucide/vue"
import type { Component } from "vue"

const { heading2, subHeading, paragraph } = useTailwindConfig()
const { careersUrl } = useAppLinks()

const listItems: Array<{
  icon: Component
  title: string
  description: string
}> = [
  {
    icon: Bolt,
    title: "Customized Talent Sourcing",
    description:
      "We tailor our recruitment process to find candidates who match your needs and company culture.",
  },
  {
    icon: ChartLine,
    title: "Streamlined Hiring Process",
    description:
      "We manage the entire recruitment lifecycle, helping you attract top talent quickly and efficiently.",
  },
]
</script>

<template>
  <HomeSection inverse>
    <template #left>
      <div v-reveal class="relative overflow-hidden rounded-2xl border border-border bg-white p-2 shadow-[0_24px_70px_rgba(16,30,68,0.12)]">
        <img class="size-full rounded-xl object-cover" src="/recruitment.png" alt="Recruitment interview">
        <div class="absolute bottom-5 left-5 z-10 flex size-fit flex-col gap-2.5 rounded-xl bg-white/92 p-5 font-display text-primary shadow-xl backdrop-blur">
          <p class="text-5xl font-semibold">99%+</p>
          <p class="max-w-40 text-base">Quick talent acquisition</p>
          <p class="flex items-center gap-1 text-xs font-medium text-green-500">
            +56%
            <CircleArrowUp class="size-4 fill-green-500 text-white" />
          </p>
        </div>
      </div>
    </template>

    <template #right>
      <div class="flex h-full flex-col justify-between">
        <div class="flex flex-col gap-5 pb-10">
          <p v-reveal class="text-sm font-semibold uppercase tracking-[0.24em] text-muted-foreground">Recruitment</p>
          <h2 v-reveal="80" :class="heading2">Recruitment Solutions tailored to your needs</h2>
          <p v-reveal="160" class="leading-7 text-muted-foreground">
            Build a hiring pipeline from job post to signed offer. SaintHR keeps the advisory feel companies already know, then layers in better sourcing, screening, and candidate visibility.
          </p>
          <BaseButton v-reveal="240" :to="careersUrl" variant="outline" class="w-fit px-6! py-4!">
            <span class="text-sm md:text-base">Partner With Us</span>
            <ArrowUpRight class="size-4" />
          </BaseButton>
        </div>

        <ul class="flex flex-col gap-4 border-t border-muted-foreground/20 pt-10">
          <li
            v-for="(list, i) in listItems"
            :key="list.title"
            v-reveal="i * 100 + 320"
            class="flex gap-3 rounded-xl bg-white/70 p-4 font-display text-sm shadow-sm transition-all duration-300 hover:-translate-y-0.5 hover:shadow-md md:text-base"
          >
            <span class="grid size-10 shrink-0 place-items-center rounded-xl bg-accent text-primary">
              <component :is="list.icon" class="size-5" :stroke-width="1.5" />
            </span>
            <div class="flex flex-col gap-2">
              <h3 :class="subHeading">{{ list.title }}</h3>
              <p :class="paragraph">{{ list.description }}</p>
            </div>
          </li>
        </ul>
      </div>
    </template>
  </HomeSection>
</template>
